// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/josuesantos1/desafio/internal/dentist"
	mock "github.com/stretchr/testify/mock"
)

// NewDentistRepository creates a new instance of DentistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDentistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DentistRepository {
	mock := &DentistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DentistRepository is an autogenerated mock type for the Repository type
type DentistRepository struct {
	mock.Mock
}

type DentistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DentistRepository) EXPECT() *DentistRepository_Expecter {
	return &DentistRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type DentistRepository
func (_mock *DentistRepository) Create(ctx context.Context, d dentist.Dentist) error {
	ret := _mock.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dentist.Dentist) error); ok {
		r0 = returnFunc(ctx, d)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DentistRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DentistRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - d dentist.Dentist
func (_e *DentistRepository_Expecter) Create(ctx any, d any) *DentistRepository_Create_Call {
	return &DentistRepository_Create_Call{Call: _e.mock.On("Create", ctx, d)}
}

func (_c *DentistRepository_Create_Call) Run(run func(ctx context.Context, d dentist.Dentist)) *DentistRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dentist.Dentist
		if args[1] != nil {
			arg1 = args[1].(dentist.Dentist)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DentistRepository_Create_Call) Return(err error) *DentistRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DentistRepository_Create_Call) RunAndReturn(run func(ctx context.Context, d dentist.Dentist) error) *DentistRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type DentistRepository
func (_mock *DentistRepository) GetByID(ctx context.Context, clinicID string, id string) (dentist.Dentist, error) {
	ret := _mock.Called(ctx, clinicID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dentist.Dentist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (dentist.Dentist, error)); ok {
		return returnFunc(ctx, clinicID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) dentist.Dentist); ok {
		r0 = returnFunc(ctx, clinicID, id)
	} else {
		r0 = ret.Get(0).(dentist.Dentist)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, clinicID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DentistRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type DentistRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - clinicID string
//   - id string
func (_e *DentistRepository_Expecter) GetByID(ctx any, clinicID any, id any) *DentistRepository_GetByID_Call {
	return &DentistRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, clinicID, id)}
}

func (_c *DentistRepository_GetByID_Call) Run(run func(ctx context.Context, clinicID string, id string)) *DentistRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DentistRepository_GetByID_Call) Return(dentist1 dentist.Dentist, err error) *DentistRepository_GetByID_Call {
	_c.Call.Return(dentist1, err)
	return _c
}

func (_c *DentistRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, clinicID string, id string) (dentist.Dentist, error)) *DentistRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type DentistRepository
func (_mock *DentistRepository) List(ctx context.Context, clinicID string, params dentist.ListParams) (dentist.ListResult, error) {
	ret := _mock.Called(ctx, clinicID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 dentist.ListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dentist.ListParams) (dentist.ListResult, error)); ok {
		return returnFunc(ctx, clinicID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dentist.ListParams) dentist.ListResult); ok {
		r0 = returnFunc(ctx, clinicID, params)
	} else {
		r0 = ret.Get(0).(dentist.ListResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, dentist.ListParams) error); ok {
		r1 = returnFunc(ctx, clinicID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DentistRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type DentistRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - clinicID string
//   - params dentist.ListParams
func (_e *DentistRepository_Expecter) List(ctx any, clinicID any, params any) *DentistRepository_List_Call {
	return &DentistRepository_List_Call{Call: _e.mock.On("List", ctx, clinicID, params)}
}

func (_c *DentistRepository_List_Call) Run(run func(ctx context.Context, clinicID string, params dentist.ListParams)) *DentistRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dentist.ListParams
		if args[2] != nil {
			arg2 = args[2].(dentist.ListParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DentistRepository_List_Call) Return(listResult dentist.ListResult, err error) *DentistRepository_List_Call {
	_c.Call.Return(listResult, err)
	return _c
}

func (_c *DentistRepository_List_Call) RunAndReturn(run func(ctx context.Context, clinicID string, params dentist.ListParams) (dentist.ListResult, error)) *DentistRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type DentistRepository
func (_mock *DentistRepository) SoftDelete(ctx context.Context, clinicID string, id string, deletedAt time.Time) error {
	ret := _mock.Called(ctx, clinicID, id, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, clinicID, id, deletedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DentistRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type DentistRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - clinicID string
//   - id string
//   - deletedAt time.Time
func (_e *DentistRepository_Expecter) SoftDelete(ctx any, clinicID any, id any, deletedAt any) *DentistRepository_SoftDelete_Call {
	return &DentistRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, clinicID, id, deletedAt)}
}

func (_c *DentistRepository_SoftDelete_Call) Run(run func(ctx context.Context, clinicID string, id string, deletedAt time.Time)) *DentistRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DentistRepository_SoftDelete_Call) Return(err error) *DentistRepository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DentistRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, clinicID string, id string, deletedAt time.Time) error) *DentistRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type DentistRepository
func (_mock *DentistRepository) Update(ctx context.Context, d dentist.Dentist) error {
	ret := _mock.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dentist.Dentist) error); ok {
		r0 = returnFunc(ctx, d)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DentistRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type DentistRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - d dentist.Dentist
func (_e *DentistRepository_Expecter) Update(ctx any, d any) *DentistRepository_Update_Call {
	return &DentistRepository_Update_Call{Call: _e.mock.On("Update", ctx, d)}
}

func (_c *DentistRepository_Update_Call) Run(run func(ctx context.Context, d dentist.Dentist)) *DentistRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dentist.Dentist
		if args[1] != nil {
			arg1 = args[1].(dentist.Dentist)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DentistRepository_Update_Call) Return(err error) *DentistRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DentistRepository_Update_Call) RunAndReturn(run func(ctx context.Context, d dentist.Dentist) error) *DentistRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoles provides a mock function for the type DentistRepository
func (_mock *DentistRepository) UpdateRoles(ctx context.Context, clinicID string, id string, in dentist.RolesInput) (dentist.Dentist, error) {
	ret := _mock.Called(ctx, clinicID, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoles")
	}

	var r0 dentist.Dentist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, dentist.RolesInput) (dentist.Dentist, error)); ok {
		return returnFunc(ctx, clinicID, id, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, dentist.RolesInput) dentist.Dentist); ok {
		r0 = returnFunc(ctx, clinicID, id, in)
	} else {
		r0 = ret.Get(0).(dentist.Dentist)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, dentist.RolesInput) error); ok {
		r1 = returnFunc(ctx, clinicID, id, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DentistRepository_UpdateRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoles'
type DentistRepository_UpdateRoles_Call struct {
	*mock.Call
}

// UpdateRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - clinicID string
//   - id string
//   - in dentist.RolesInput
func (_e *DentistRepository_Expecter) UpdateRoles(ctx any, clinicID any, id any, in any) *DentistRepository_UpdateRoles_Call {
	return &DentistRepository_UpdateRoles_Call{Call: _e.mock.On("UpdateRoles", ctx, clinicID, id, in)}
}

func (_c *DentistRepository_UpdateRoles_Call) Run(run func(ctx context.Context, clinicID string, id string, in dentist.RolesInput)) *DentistRepository_UpdateRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 dentist.RolesInput
		if args[3] != nil {
			arg3 = args[3].(dentist.RolesInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DentistRepository_UpdateRoles_Call) Return(dentist1 dentist.Dentist, err error) *DentistRepository_UpdateRoles_Call {
	_c.Call.Return(dentist1, err)
	return _c
}

func (_c *DentistRepository_UpdateRoles_Call) RunAndReturn(run func(ctx context.Context, clinicID string, id string, in dentist.RolesInput) (dentist.Dentist, error)) *DentistRepository_UpdateRoles_Call {
	_c.Call.Return(run)
	return _c
}
