// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/josuesantos1/desafio/internal/payment"
	mock "github.com/stretchr/testify/mock"
)

// NewPaymentRepository creates a new instance of PaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepository {
	mock := &PaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentRepository is an autogenerated mock type for the Repository type
type PaymentRepository struct {
	mock.Mock
}

type PaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentRepository) EXPECT() *PaymentRepository_Expecter {
	return &PaymentRepository_Expecter{mock: &_m.Mock}
}

// Approve provides a mock function for the type PaymentRepository
func (_mock *PaymentRepository) Approve(ctx context.Context, id string, approvedAt time.Time) error {
	ret := _mock.Called(ctx, id, approvedAt)

	if len(ret) == 0 {
		panic("no return value specified for Approve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, approvedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PaymentRepository_Approve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Approve'
type PaymentRepository_Approve_Call struct {
	*mock.Call
}

// Approve is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - approvedAt time.Time
func (_e *PaymentRepository_Expecter) Approve(ctx any, id any, approvedAt any) *PaymentRepository_Approve_Call {
	return &PaymentRepository_Approve_Call{Call: _e.mock.On("Approve", ctx, id, approvedAt)}
}

func (_c *PaymentRepository_Approve_Call) Run(run func(ctx context.Context, id string, approvedAt time.Time)) *PaymentRepository_Approve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PaymentRepository_Approve_Call) Return(err error) *PaymentRepository_Approve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PaymentRepository_Approve_Call) RunAndReturn(run func(ctx context.Context, id string, approvedAt time.Time) error) *PaymentRepository_Approve_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type PaymentRepository
func (_mock *PaymentRepository) Create(ctx context.Context, p payment.Payment) (payment.Payment, bool, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 payment.Payment
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.Payment) (payment.Payment, bool, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.Payment) payment.Payment); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(payment.Payment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, payment.Payment) bool); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, payment.Payment) error); ok {
		r2 = returnFunc(ctx, p)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PaymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PaymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p payment.Payment
func (_e *PaymentRepository_Expecter) Create(ctx any, p any) *PaymentRepository_Create_Call {
	return &PaymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *PaymentRepository_Create_Call) Run(run func(ctx context.Context, p payment.Payment)) *PaymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 payment.Payment
		if args[1] != nil {
			arg1 = args[1].(payment.Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentRepository_Create_Call) Return(result payment.Payment, created bool, err error) *PaymentRepository_Create_Call {
	_c.Call.Return(result, created, err)
	return _c
}

func (_c *PaymentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, p payment.Payment) (payment.Payment, bool, error)) *PaymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type PaymentRepository
func (_mock *PaymentRepository) GetByID(ctx context.Context, id string) (payment.Payment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 payment.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (payment.Payment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) payment.Payment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(payment.Payment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PaymentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PaymentRepository_Expecter) GetByID(ctx any, id any) *PaymentRepository_GetByID_Call {
	return &PaymentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *PaymentRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *PaymentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentRepository_GetByID_Call) Return(payment1 payment.Payment, err error) *PaymentRepository_GetByID_Call {
	_c.Call.Return(payment1, err)
	return _c
}

func (_c *PaymentRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (payment.Payment, error)) *PaymentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
