// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/josuesantos1/desafio/internal/clinic"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Repository
func (_mock *Repository) Create(ctx context.Context, c clinic.Clinic) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clinic.Clinic) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c clinic.Clinic
func (_e *Repository_Expecter) Create(ctx any, c any) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, c)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, c clinic.Clinic)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clinic.Clinic
		if args[1] != nil {
			arg1 = args[1].(clinic.Clinic)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Create_Call) Return(err error) *Repository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(ctx context.Context, c clinic.Clinic) error) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByDocument provides a mock function for the type Repository
func (_mock *Repository) GetByDocument(ctx context.Context, document string) (clinic.Clinic, error) {
	ret := _mock.Called(ctx, document)

	if len(ret) == 0 {
		panic("no return value specified for GetByDocument")
	}

	var r0 clinic.Clinic
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (clinic.Clinic, error)); ok {
		return returnFunc(ctx, document)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) clinic.Clinic); ok {
		r0 = returnFunc(ctx, document)
	} else {
		r0 = ret.Get(0).(clinic.Clinic)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, document)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetByDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByDocument'
type Repository_GetByDocument_Call struct {
	*mock.Call
}

// GetByDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - document string
func (_e *Repository_Expecter) GetByDocument(ctx any, document any) *Repository_GetByDocument_Call {
	return &Repository_GetByDocument_Call{Call: _e.mock.On("GetByDocument", ctx, document)}
}

func (_c *Repository_GetByDocument_Call) Run(run func(ctx context.Context, document string)) *Repository_GetByDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetByDocument_Call) Return(clinic1 clinic.Clinic, err error) *Repository_GetByDocument_Call {
	_c.Call.Return(clinic1, err)
	return _c
}

func (_c *Repository_GetByDocument_Call) RunAndReturn(run func(ctx context.Context, document string) (clinic.Clinic, error)) *Repository_GetByDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type Repository
func (_mock *Repository) GetByID(ctx context.Context, id string) (clinic.Clinic, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 clinic.Clinic
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (clinic.Clinic, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) clinic.Clinic); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(clinic.Clinic)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Repository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) GetByID(ctx any, id any) *Repository_GetByID_Call {
	return &Repository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *Repository_GetByID_Call) Run(run func(ctx context.Context, id string)) *Repository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetByID_Call) Return(clinic1 clinic.Clinic, err error) *Repository_GetByID_Call {
	_c.Call.Return(clinic1, err)
	return _c
}

func (_c *Repository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (clinic.Clinic, error)) *Repository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type Repository
func (_mock *Repository) SoftDelete(ctx context.Context, id string, deletedAt time.Time) error {
	ret := _mock.Called(ctx, id, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, deletedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type Repository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - deletedAt time.Time
func (_e *Repository_Expecter) SoftDelete(ctx any, id any, deletedAt any) *Repository_SoftDelete_Call {
	return &Repository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id, deletedAt)}
}

func (_c *Repository_SoftDelete_Call) Run(run func(ctx context.Context, id string, deletedAt time.Time)) *Repository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_SoftDelete_Call) Return(err error) *Repository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id string, deletedAt time.Time) error) *Repository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Repository
func (_mock *Repository) Update(ctx context.Context, c clinic.Clinic) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clinic.Clinic) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - c clinic.Clinic
func (_e *Repository_Expecter) Update(ctx any, c any) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, c)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, c clinic.Clinic)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clinic.Clinic
		if args[1] != nil {
			arg1 = args[1].(clinic.Clinic)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Update_Call) Return(err error) *Repository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(ctx context.Context, c clinic.Clinic) error) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}
